language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install -y capnproto libcapnp-dev
env:
  global:
    - ALCOTEST_SHOW_ERRORS=1
    - PINS="irmin.dev:--dev irmin-mem.dev:--dev irmin-fs.dev:--dev irmin-http.dev:--dev irmin-graphql.dev:https://github.com/mirage/irmin.git irmin-git.dev:--dev irmin-mirage.dev:--dev irmin-unix.dev:--dev irmin-rpc.dev:. irmin-rpc-unix.dev:. irmin-rpc-mirage.dev:."
  matrix:
    - OCAML_VERSION=4.08 PACKAGE="irmin-rpc.dev" TESTS=true
    - OCAML_VERSION=4.08 PACKAGE="irmin-rpc-unix.dev" TESTS=false
    - OCAML_VERSION=4.08 PACKAGE="irmin-rpc-mirage.dev" TESTS=false
